### PR TITLE
Improve packaging

### PR DESCRIPTION
**Pull request by FedericoCeratto**
Fix package, executable and desktop icon naming.
Enable security/hardening flags.

### CODE REVIEW

**Comment by bleakgrey** [comment]
Tootle is elementary OS centric right now and has to follow AppCenter's publication guidelines. AppCenter enforces the Reverse Domain Name Notation (RDNN) for packages and binary names and I'm pretty sure this PR will break the automated verification.

I use the name `com.github.bleakgrey.tootle` thorough the entire project code for consistency and to avoid naming collisions, so the package, binary and desktop entry should be left intact.

**Comment by FedericoCeratto** [comment]
@bleakgrey I'll revert some of the changes.

**Comment by FedericoCeratto** [comment]
@bleakgrey ready

**Comment by bleakgrey** [comment]
Hey there, sorry for the delay. I'll test this with the new Juno release and merge the PR when I'm sure the auto packaging isn't broken.

Thank you for your contribution!

**Comment by FedericoCeratto** [comment]
@bleakgrey ping?

**Comment by bleakgrey** [comment]
Let's see what Houston says about it...

**Comment by bleakgrey** [comment]
Looks good to go! Thanks, and sorry for the delay.

**Pull request merged**
