### PR TITLE
Drop executable bit from most files

### PR DESCRIPTION
**Pull request by bugaevc**
Noticed all the files had `+x` bit set.

### CODE REVIEW

**Comment by bleakgrey** [comment]
Ohhh no, I made a typo and entered `git add /` in the terminal... 🌵

**Comment by bugaevc** [comment]
Hm, so you didn't merge the add shebangs commit? May I ask why?

**Comment by bleakgrey** [comment]
But I did 😕 
All 3 files have shebangs now, don't they?

**Comment by bugaevc** [comment]
Ahh, indeed. You must have squashed the two commits I to one, while using the commit message from the second one. Fine with me, just a little bit confusing 🙂

**Pull request merged**
