### PR TITLE
Fallback to xdg-open when opening URLs

### PR DESCRIPTION
**Pull request by FedericoCeratto**
Hello and thanks for developing Tootle. Would you consider accepting a little fallback mechanism for opening URLs?
Is the URI validated/escaped in order to avoid command injection vulnerabilities?
Thanks!

### CODE REVIEW

**Comment by alcinnz** [comment]
I'm not involved in the development of Tootle, but I've had to get quite familiar with how elementary OS and other free desktops handle URLs for my own app.

And the code Tootle uses to open URLs is the same as that used by xdg-open, so I'd advise that a more useful fallback would be to search the AppCenter (or other package manager) for relevant apps. I can advise on how to do that.

I'm not sure what the story is or should be on validation.

**Comment by FedericoCeratto** [comment]
@alcinnz the change has been tested on a Debian desktop and the fallback allowed the user to open URLs.

**Comment by bleakgrey** [comment]
I'd accept this PR gladly if it could fix the app's behavior in a Flatpak environment. Honestly, I'm not really sure if Flatpak's sandbox will even allow running `xdg-open`. Maybe @cagatay-y has any ideas?

Also, I don't think that the URIs need to be escaped. Tootle usually uses this command to open links to other posts and Mastodon should takes care of the necessary URI sanitizing.

**Comment by cagatay-y** [comment]
Looks like xdg-open is available inside the sandbox. I will check with a build with the PR.

**Comment by kenvandine** [comment]
I'm quite interested in this.  I created a snap for tootle and needed to patch it to use xdg-open.

**Pull request merged**
