### PR TITLE
new-account: Slight redesign

### PR DESCRIPTION
**Pull request by Kekun**
This makes the code simpler, implements the latest GNOME HIG standard,
gives a back gesture, and makes the dialog it fit phones.

### CODE REVIEW

**Comment by bleakgrey** [comment]
I can't seem to make `libhandy` compile as a meson submodule. The compilation fails with `error: Package `fribidi' not found in specified Vala API directories or GObject-Introspection GIR directories`.

**Comment by Kekun** [comment]
We depend on it since yesterday to correctly handle text direction in our new `HdyTabBar` widget.

I'd suggest, if possible, to not include libhandy as a submodule and to use it from the master GNOME SDK. Alternatively: include fribidi as a submodule or use an older commit in your submodule.

**Comment by Kekun** [comment]
Or maybe just install fribidi in your CI, it's a very stable lib, as in Debian Stable: it didn't evolve since years, so it won't be an issue.

**Comment by Kekun** [comment]
Anyway, that's completely unrelated to that MR.

**Pull request merged**
