### PR TITLE
Icon Redesign

### PR DESCRIPTION
**Pull request by Fatih20**
The previous icon didn't comply by the eOS HIG regarding the implementation of pictogram. It should be extruded or inset. So, I modified the icon to fix this. Also, there is some spilling of the highlight outline because it wasn't masked.

### CODE REVIEW

**Comment by bleakgrey** [comment]
I no longer have plans to support this project the way it is for elementary OS, which makes their guidelines irrelevant.

I like your updated dark trumpet symbol though. I may consider using it in the next version.

**Comment by bleakgrey** [comment]
Oh, it looks like changed files lost their crispness for some reason. Did you change the dimensions?

**Comment by Fatih20** [comment]
Check it in the document properties if I did some mistake. Like how? I don't think that should happen.

**Comment by bleakgrey** [comment]
I'm comparing differences with GitHub's swipe mode. The icon dimensions are mismatched, visibly diluting outlines.

Screenshot from 2019-08-05 02-42-18

**Comment by Fatih20** [comment]
I modified the icon dimension to comply with the [eOS HIG](https://elementary.io/docs/human-interface-guidelines). You can change it if you want.

**Comment by Fatih20** [comment]
So, like, any changes for it until it can be merged?

**Comment by bleakgrey** [comment]
Superseded by #162

**Pull request closed without merging**
