### PR TITLE
Fix and unify way of loading images

### PR DESCRIPTION
**Pull request by cleac**
This will drastically improve way of loading images:

1. Loading of images now will be unified, so it will be easier to write caching of already downloaded loaded images
2. Images are now loaded without injecting authorization headers (not sure if they are needed here)

I think this code is pretty bad, and I am going to improve it. I would be very happy to get a feedback, which parts are the worst 😉️

### CODE REVIEW

**Comment by bleakgrey** [comment]
`queue` method should never have equivalents as it creates fragmentation instead of leaving a single entry point for network requests. In this case, `queue_noauth` is excess because requests are never injected with auth tokens unless specified explicitly with `network.inject (msg, Network.INJECT_TOKEN)`.

**Comment by bleakgrey** [comment]
Except that `queue_noauth` part, I like the rest of the code. It does make caching easier for the future.

**Comment by cleac** [comment]
What about then making all the requests authorized as a default and disable auth only for some conditions? It's just feels a bit strange to me: to make a additional step to _make_ a request to be authorized.

**Comment by bleakgrey** [comment]
Reversing the idea would probably reduce the required boilerplate code to make an authorized request, but it's not code line amount that counts.

Each `network.inject (msg, Network.INJECT_TOKEN)` line is a reminder for the developer (i.e. me) that a request can be a potential credential leak if wrong URL is used or mismatched. And I tend to forget such details a lot.

It's always better to be safe rather than chancing to accidentally leak user account credentials.

**Comment by bleakgrey** [comment]
No longer relevant for `master`

**Pull request closed without merging**
