### PR TITLE
fix 'gtk_window_set_titlebar() called on a realized window' warning

### PR DESCRIPTION
**Pull request by martensitingale**
At startup, Tootle (with GTK+3.22.30) prints a `Gtk-WARNING` which states `gtk_window_set_titlebar() called on a realized window`; fix this by moving the call into the construct block.

### CODE REVIEW

**Comment by bleakgrey** [comment]
Tootle is elementary OS oriented right now and currently the most recent gtk version in its repos is 3.18.

I understand that Tootle has a lot of "deprecated is deprecated" stuff but hopefully it will be changed in eOS Juno

**Comment by martensitingale** [comment]
This particular warning occurs at runtime and should be fixable in a way compatible even with old library versions by simply moving the function call as this PR does. Does it not compile/work with the library versions on eOS? I don't have a way to test at present but it seems like it should work ok.

The other open PR I have does depend on GTK 3.20, so it's blocked on eOS updates. It might be best to just close it and post an issue noting that there are build warnings waiting on eOS to update its GTK+ version.

**Comment by bleakgrey** [comment]
Doesn't seem to be breaking anything, so I merged this. Thanks!

**Comment by bleakgrey** [comment]
Turns out it actually breaks maximize button on eOS, it just stops working. I'm going to revert this for now and merge again when eOS Juno is out.

**Comment by alcinnz** [comment]
Weird. Maximize works fine for Odysseus and is error free.

**Comment by bleakgrey** [comment]
Maybe it's something specific for Tootle. I'm not really sure, I just reverted all header related changes and it started working again.

**Pull request merged**
